repositories {
    mavenLocal()
    mavenCentral()
    // force gradle to download FastUtil & LWJGL from the central maven so we can get source artifacts
    exclusiveContent { // Force
        forRepository { mavenCentral() }
        filter {
            includeGroup("it.unimi.dsi")
            includeGroup("org.lwjgl")
        }
    }
    maven {
        url = "https://maven.quiltmc.org/repository/release/"
    }
    maven { // JEI
        name = "Jared's Maven"
        url = "https://maven.blamejared.com/"
    }
    maven { // JEI mirror, AE2
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
    exclusiveContent { // terraformers - EMI
        forRepository { maven { url = "https://maven.terraformersmc.com/releases/" } }
        filter { includeGroup("dev.emi") }
    }
    exclusiveContent { // Modrinth Maven
        forRepository { maven { url = "https://api.modrinth.com/maven" } }
        filter { includeGroup("maven.modrinth") }
    }
    exclusiveContent { // Curseforge Maven
        forRepository { maven { url = "https://cursemaven.com" } }
        filter { includeGroup("curse.maven") }
    }
}
