org.gradle.jvmargs = -Xmx6G
org.gradle.java.installations.auto-download=false
org.gradle.parallel = true
org.gradle.caching = true

# Mod Info
mod_id = synceddata
mod_name = SyncedData
mod_version = 0.0.2
mod_description =
mod_license = GNU AGPL 3.0
mod_url = https://github.com/ModularMCLib/SyncedData/
mod_issue_tracker = https://github.com/ModularMCLib/SyncedData/issues/
maven_group = com.modularmc.synceddata
